title: PILLAR
remote_theme: carlosperate/jekyll-theme-rtd
repo_url: "https://github.com/carlosperate/jekyll-theme-rtd"
edit_on_github: false
sticky_navigation: true
prev_next_buttons_location: bottom
search_enabled: true
hljs_style: github-gist
collections:
  order:
    -index.html
    -Muscular_Anatomy
    -Scans
    -End_Matter
